# Generated by Django 5.1.5 on 2025-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('I', 'Ingredients'), ('R', 'Recipe')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
