# Generated by Django 5.1.5 on 2025-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_recipe_country_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=2),
        ),
    ]
